CREATE TABLE IF NOT EXISTS public.demandes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120) NOT NULL,
    phone          VARCHAR(40)  NOT NULL,
    trip_type      VARCHAR(10)  NOT NULL DEFAULT 'simple',
    direction      VARCHAR(10)  NULL,
    address        VARCHAR(255) NULL,
    from_address   VARCHAR(255) NULL,
    to_address     VARCHAR(255) NULL,
    goods_type     VARCHAR(40)  NOT NULL DEFAULT 'other',
    preferred_date DATE NULL,
    notes          TEXT NULL,
    lang           VARCHAR(5)   NOT NULL DEFAULT 'fr',
    status         VARCHAR(20)  NOT NULL DEFAULT 'new',
    admin_note     VARCHAR(255) NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT demandes_trip_type_check CHECK (trip_type IN ('simple', 'double')),
    CONSTRAINT demandes_direction_check CHECK (direction IS NULL OR direction IN ('pickup', 'deliver')),
    CONSTRAINT demandes_status_check CHECK (status IN ('new', 'contacted', 'confirmed', 'done'))
);

CREATE INDEX IF NOT EXISTS idx_demandes_created_at ON public.demandes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_demandes_status ON public.demandes (status);
